version: '3.9'

services:
  db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: shorterms-db
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PWD
    volumes:
      - shorterms_db:/var/lib/postgresql/data
    ports:
      - $DB_HOST:$DB_PORT:5432

volumes:
  shorterms_db: