name: Fly CD Pipeline

on:
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Fly Deployment
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: FLY_API_TOKEN=$FLY_API_TOKEN flyctl deploy --remote-only
